//
//  wCalendarTests.m
//  wCalendarTests
//
//  Created by masumiya on 2013/02/03.
//  Copyright (c) 2013年 masumiya. All rights reserved.
//

#import "wCalendarJpTests.h"

#import "wCalendarJp.h"

@implementation wCalendarJpTests

- (void)setUp
{
    [super setUp];
    
    // Set-up code here.
    cal_jp = [[wCalendarJp alloc] init];
    STAssertNotNil(cal_jp, @"cannot create wCalendarJp instance.");
}

- (void)tearDown
{
    // Tear-down code here.
    cal_jp = nil;
    NSLog(@"%@ tearDown.", self.name);
    
    [super tearDown];
}

- (void)testIsHoliday
{
    int year, month;
    NSString *message = @"failed. isn't holiday.[%d / %d / %d]";
    NSLog(@"%@ start.", self.name);
    // 2013/1
    year = 2013;
    month = 1;
    STAssertTrue([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertTrue([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/2
    year = 2013;
    month = 2;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertTrue([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    // 2013/3
    year = 2013;
    month = 3;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertTrue([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/4
    year = 2013;
    month = 4;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertTrue([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    // 2013/5
    year = 2013;
    month = 5;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertTrue([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertTrue([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertTrue([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertTrue([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/6
    year = 2013;
    month = 6;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    // 2013/7
    year = 2013;
    month = 7;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertTrue([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/8
    year = 2013;
    month = 8;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/9
    year = 2013;
    month = 9;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertTrue([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertTrue([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    // 2013/10
    year = 2013;
    month = 10;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertTrue([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertFalse([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    // 2013/11
    year = 2013;
    month = 11;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertTrue([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertTrue([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertTrue([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    // 2013/12
    year = 2013;
    month = 12;
    STAssertFalse([cal_jp isHoliday:year month:month day:1 ], message, year, month, 1);
    STAssertFalse([cal_jp isHoliday:year month:month day:2 ], message, year, month, 2);
    STAssertFalse([cal_jp isHoliday:year month:month day:3 ], message, year, month, 3);
    STAssertFalse([cal_jp isHoliday:year month:month day:4 ], message, year, month, 4);
    STAssertFalse([cal_jp isHoliday:year month:month day:5 ], message, year, month, 5);
    STAssertFalse([cal_jp isHoliday:year month:month day:6 ], message, year, month, 6);
    STAssertFalse([cal_jp isHoliday:year month:month day:7 ], message, year, month, 7);
    STAssertFalse([cal_jp isHoliday:year month:month day:8 ], message, year, month, 8);
    STAssertFalse([cal_jp isHoliday:year month:month day:9 ], message, year, month, 9);
    STAssertFalse([cal_jp isHoliday:year month:month day:10 ], message, year, month, 10);
    STAssertFalse([cal_jp isHoliday:year month:month day:11 ], message, year, month, 11);
    STAssertFalse([cal_jp isHoliday:year month:month day:12 ], message, year, month, 12);
    STAssertFalse([cal_jp isHoliday:year month:month day:13 ], message, year, month, 13);
    STAssertFalse([cal_jp isHoliday:year month:month day:14 ], message, year, month, 14);
    STAssertFalse([cal_jp isHoliday:year month:month day:15 ], message, year, month, 15);
    STAssertFalse([cal_jp isHoliday:year month:month day:16 ], message, year, month, 16);
    STAssertFalse([cal_jp isHoliday:year month:month day:17 ], message, year, month, 17);
    STAssertFalse([cal_jp isHoliday:year month:month day:18 ], message, year, month, 18);
    STAssertFalse([cal_jp isHoliday:year month:month day:19 ], message, year, month, 19);
    STAssertFalse([cal_jp isHoliday:year month:month day:20 ], message, year, month, 20);
    STAssertFalse([cal_jp isHoliday:year month:month day:21 ], message, year, month, 21);
    STAssertFalse([cal_jp isHoliday:year month:month day:22 ], message, year, month, 22);
    STAssertTrue([cal_jp isHoliday:year month:month day:23 ], message, year, month, 23);
    STAssertFalse([cal_jp isHoliday:year month:month day:24 ], message, year, month, 24);
    STAssertFalse([cal_jp isHoliday:year month:month day:25 ], message, year, month, 25);
    STAssertFalse([cal_jp isHoliday:year month:month day:26 ], message, year, month, 26);
    STAssertFalse([cal_jp isHoliday:year month:month day:27 ], message, year, month, 27);
    STAssertFalse([cal_jp isHoliday:year month:month day:28 ], message, year, month, 28);
    STAssertFalse([cal_jp isHoliday:year month:month day:29 ], message, year, month, 29);
    STAssertFalse([cal_jp isHoliday:year month:month day:30 ], message, year, month, 30);
    STAssertFalse([cal_jp isHoliday:year month:month day:31 ], message, year, month, 31);
    NSLog(@"%@ end.", self.name);
}

@end
